### ISSUE TITLE
[BUG] Suppress warnings from depricated packages

### ISSUE THREAD

**Issue by bradley-erickson** [bradley-erickson/CmyPlot#12]
**Describe the bug**
Dash Bootstrap components have not been updated to Dash 2.0.0 yet. This causes a warning message to appear in the run console when the server is running. We should suppress this.

**Expected behavior**
Message does not appear.

**Comment by aakriti0fnu** [comment]
@bradley-erickson, resolved the issue, no need of suppressing the warning. The[ pre-release version takes care of it](https://pypi.org/project/dash-bootstrap-components/1.0.0b2/). pushed changes on my branch, making a pull request to merge to `main`.

**Comment by bradley-erickson** [comment]
We will also need to update some of the other issues.
#23
