### ISSUE TITLE
[LOGISTICS] Create video showcasing project

### ISSUE THREAD

**Issue by bradley-erickson** [bradley-erickson/CmyPlot#16]
**What needs to happen in the codebase?**
Include video showcasing project

**Comment by bradley-erickson** [comment]
This should follow suit of other videos, where it starts with a simple problem you have then proceeds to explain the site and it's primary use case.

**Comment by aakriti0fnu** [comment]
Video is created and added to the [Readme](https://user-images.githubusercontent.com/65619749/134620802-5fac9f0e-d697-49df-876c-3f5ff7d86e38.mp4
)
It is also under the aakriti_dev branch in docs/demo
