### ISSUE TITLE
Adding user login/signup functionality to the app.

### ISSUE THREAD

**Issue by aakriti0fnu** [bradley-erickson/CmyPlot#32]
Description: The users would be able to log in or sign up for our app. 
                    Their login credential will be securely stored in the backend database. 
                    Only the authenticated users would be allowed 
                                  to enter the site, 
                                  upload the csv data and 
                                  visualise it.
                    Later, we can extend this functionality by letting the users save their plots and csv data.

**Comment by bradley-erickson** [comment]
Duplicates #20

**Comment by bradley-erickson** [comment]
Removing this ticket as it is a duplicate.
